# Site settings
title: ARDIANSYAH
description: '<p>Mahasiswa Sistem Informasi TA 2014</p>
              <p>Fakultas : Sains dan Teknologi</p>
              <p>Universitas Islam Negeri Sultan Syarif Kasim Riau</p>'
url: 'http://Ardiansyah022.github.io'
baseurl: '/Ardiansyah022.github.io/'
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ardiansyah
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Universitas Islam Negeri Sultan Syarif Kasim Riau
email: ardiansyah541996@gmail.com
twitter_username: ardiansyah
github_username:  ardiansyah022
gplus_username:  ardiansyah
linkedin_username: ardiansyah
uin suska: http://uin-suska.ac.id/
sif uin: http://sif.uin-suska.ac.id/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
     values:
        layout: 'post'
        
# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rounge

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
