# Site settings
title: ARDIANSYAH
description: '<p>Universitas Islam Negeri Sultan Syarif Kasim Riau</p>'
url: 'http://Ardiansyah.github.io'
baseurl: '/Ardiansyah.github.io/'
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ardiansyah
user_description: Mahasiswa Sistem Informasi TA 2014 Fakultas Sains dan Teknologi
user_title: Universitas Islam Negeri Sultan Syarif Kasim Riau
email: ardiansyah541996@gmail.com
twitter_username: ardiansyah
github_username:  ardiansyah022
gplus_username:  ardiansyah
linkedin_username: ardiansyah
uin suska: http://uin-suska.ac.id/
sif uin: http://sif.uin-suska.ac.id/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
     values:
        layout: 'post'
        
# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rounge

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
